---
title: "bac"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
params:
  out: "/Users/dnanto/GitHub/dissertation/out/FJ643676.1"
  tsv: "/Users/dnanto/GitHub/dissertation/data/genbank/10508.tsv"
  xls: "/Users/dnanto/GitHub/dissertation/data/meta/HAdV.xlsx"
  bin: 0.10
  cpu: !r parallel::detectCores()
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(BactDating)
  library(ape)
  library(ggtree)
})
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df.meta <- read_tsv(params$tsv, col_types = cols(date = "D", .default = "c"), na = "?")
df.type <- openxlsx::read.xlsx(params$xls, sheet = "type")
```

```{r}
models <-
  list.files(params$out, "\\.qs$", full.names = T) %>%
  parallel::mclapply(function(path) {
    res <- qs::qread(path)
    keys <- c("likelihood", "prior", "mu", "sigma", "alpha", "root")
    logs <- as.data.frame(res$record[, keys])
    burn <- max(1, round(nrow(logs) * params$bin))
    mcmc <- coda::as.mcmc(res$record[burn:nrow(logs), keys])
    c(
      path = path,
      model = res$model,
      dic = res$dic,
      ess = coda::effectiveSize(mcmc),
      est = apply(res$record[, head(keys, -1)], 2, function(val) {
        val <- sort(val)
        vals <- c(median(val), val[pmax(1, floor(length(val) * c(0.025, 0.975)))])
        sprintf("%.2f [%.2f;%.2f]", vals[1], vals[2], vals[3])
      }),
      est.root = with(
        res,
        sprintf("%.2f [%.2f;%.2f]", tree$root.time, CI[Ntip(tree) + 1, 1], CI[Ntip(tree) + 1, 2])
      )
    )
  }, mc.cores = params$cpu) %>%
  bind_rows() %>%
  mutate(dic = as.numeric(dic))
```

```{r}
select(models, path, model, dic, starts_with("ess")) %>%
  mutate(path = str_match(path, "(\\d+)\\.qs$")[, 2]) %>%
  rename(itr = path) %>%
  arrange(dic)
```

```{r}
select(models, path, model, dic, starts_with("est")) %>%
  mutate(path = str_match(path, "(\\d+)\\.qs$")[, 2]) %>%
  rename(itr = path) %>%
  arrange(dic)
```

```{r}
res <- slice_min(models, dic) %>% pull(path) %>% qs::qread(nthreads = params$cpu)
```

```{r, fig.width=10, fig.height=4}
res$inputtree$tip.date <- decimal_date(
  ymd(str_match(res$inputtree$tip.label, "(\\d{4}-\\d{2}-\\d{2})$")[, 2])
)
invisible(roottotip(res$inputtree, res$inputtree$tip.date))
plot(res, "scatter")
```

```{r, fig.width=10, fig.height=2}
plot(res, "trace")
```

```{r}
tdat <- as.treedata.resBactDating(res)
mrsd <- min(str_match(tdat[[1]]$tip.label, "(\\d{4}-\\d{2}-\\d{2})$")[, 2])
tdat[[1]]$tip.label <- str_remove(tdat[[1]]$tip.label, "_\\d{4}-\\d{2}-\\d{2}$")

tree <- methods::new("treedata", phylo = tdat[[1]], data = tibble::as_tibble(tdat[[2]]))
type <- with(
  df.type[match(tree@phylo$tip.label, df.type$accver), ],
  paste(species, type, sep = "-")
)

tree@phylo <- groupOTU(tree@phylo, split(tree@phylo$tip.label, type), "type")

ggtree(tree, mrsd = mrsd, size = 1) +
  aes(color = type) +
  # geom_nodelab(color = "black", size = 6) +
  # geom_tiplab(linesize = 1, align = T, color = "black") +
  geom_range("height_0.95_HPD", alpha = 0.5, size = 4) +
  theme_tree2() +
  theme(
    legend.position = "bottom",
    panel.grid.major.x = element_line(color = "black", size = .25),
    panel.grid.minor.x = element_line(color = "grey", size = .25)
  ) ->
  p.bac
```

```{r}
ape::read.gff(file.path(params$out, "gub.recombination_predictions.gff")) %>%
  select(start, end, attributes) %>%
  apply(1, function(row) {
    attr <- str_split_fixed(Filter(nchar, str_split(row[["attributes"]], ";")[[1]]), "=", 2)
    attr[, 2] <- substr(attr[, 2], 2, nchar(attr[, 2]) - 1)
    attr <- setNames(attr[, 2], attr[, 1])
    taxa <- Filter(nchar, str_split(attr[["taxa"]], " ")[[1]])
    data.frame(
      taxa, t(row[c("start", "end")]), t(attr[setdiff(names(attr), "taxa")]), 
      stringsAsFactors = F
    )
  }) %>%
  bind_rows() %>%
  mutate_at("neg_log_likelihood", as.numeric) %>%
  mutate_at(c("start", "end", "snp_count"), as.integer) %>%
  mutate(date = str_match(taxa, "(\\d{4}-\\d{2}-\\d{2})$")[, 2]) %>%
  mutate(taxa = factor(
    str_remove(taxa, "_\\d{4}-\\d{2}-\\d{2}$"), 
    levels = rev(get_taxa_name(p.bac))
  )) %>%
  add_count(start, end) %>%
  mutate(unique = n == 1) ->
  gff

ggplot() +
  geom_rect(
    data = gff,
    aes(
      xmin = start, ymin = as.numeric(taxa) - 0.5, xmax = end, ymax = as.numeric(taxa) + 0.5,
      fill = unique, alpha = snp_count
    )
  ) +
  scale_alpha_continuous() + 
  scale_y_discrete(limits = levels(gff$taxa)) +
  theme_minimal() +
  theme(legend.position = "bottom") ->
  p.gff
```

```{r, fig.width=10, fig.height=10}
cowplot::plot_grid(p.bac, p.gff, ncol = 2, align = "h", rel_widths = c(2, 1))
```

