---
title: "bac2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
params:
  out: "/Users/dnanto/GitHub/dissertation/out/AY594253.1/AAT97450.1"
  tsv: "/Users/dnanto/GitHub/dissertation/data/genbank/10508.tsv"
  xls: "/Users/dnanto/GitHub/dissertation/data/meta/HAdV.xlsx"
  cpu: !r parallel::detectCores()
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggtree)
})
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
enframe(unlist(params), "key", "val")
```

```{r}
runs <- qs::qread(file.path(params$out, "bact.qs"), nthreads = params$cpu)
```

```{r}
run <- runs[[which.min(sapply(runs, "[[", "dic"))]]
```

```{r, fig.height=2, fig.width=10}
plot(run, "trace")
```

```{r}
coda::effectiveSize(BactDating::as.mcmc.resBactDating(run, burnin = params$brn))
```

```{r}
df.meta <- read_tsv(params$tsv, col_types = cols(date = "D", .default = "c"), na = "?")
df.type <- openxlsx::read.xlsx(params$xls, sheet = "type")

tdat <- BactDating::as.treedata.resBactDating(run)
tdat[[1]]$tip.label <- str_remove(tdat[[1]]$tip.label, "_\\d{4}-\\d{2}-\\d{2}$")
tree <- methods::new("treedata", phylo = tdat[[1]], data = tibble::as_tibble(tdat[[2]]))
tip.idx <- match(tree@phylo$tip.label, df.type$accver)
tip.type <- with(df.type[tip.idx, ], paste(species, type, sep = "-"))
tip.date <- df.meta[match(tree@phylo$tip.label, df.meta$accver), ]$date

tree@phylo <- groupOTU(tree@phylo, split(tree@phylo$tip.label, tip.type), "type")
```

```{r, fig.width=10, fig.height=20}
ggtree(tree, mrsd = min(tip.date), size = 2) +
  aes(color = type) +
  geom_nodelab(color = "black", size = 6) +
  geom_tiplab(linesize = 1, align = T, color = "black") +
  geom_range("height_0.95_HPD", alpha = 0.5, size = 4) +
  theme_tree2() +
  theme(
    legend.position = "bottom",
    panel.grid.major.x = element_line(color="black", size = .25),
    panel.grid.minor.x = element_line(color="grey", size = .25)
  )
ggsave(file.path(params$out, "bact.pdf"))
```
