acc: "AY594253.1"
pid: "AAT97450.1"
fdb: "/Users/dnanto/GitHub/dissertation/data/genbank/10508.db"
bdb: "/Users/dnanto/GitHub/dissertation/data/blast/10508"
tsv: "/Users/dnanto/GitHub/dissertation/data/genbank/10508.tsv"
out: "/Users/dnanto/GitHub/dissertation/out"
