$schema: "http://json-schema.org/draft-06/schema#"

description: the parameters for the measurably-evolving population workflow

properties:

  # ffbio
  acc:
    description: the accession of the query record
  pid:
    type: string
    description: the protein id of the query record
  fdb:
    type: string
    description: the ffbio database of GenBank sequence records

  # BLAST+
  bdb:
    type: string
    description: the BLAST database name

  # filter
  tsv:
    type: string
    description: the tab-separated values file mapping "accver" to "date"
    default: False
  thr:
    type: number
    description: the query percent identity coverage >= threshold in [0, 100]
    default: 85

  # Gubbins
  itr:
    type: integer
    description: the maximum number of iterations
    default: 10
  gap:
    type: integer
    description: the value to filter out taxa with more than this percentage of gaps
    default: 25

  # BactDating
  model:
    type: array
    description: the models to use (poisson, negbin, strictgamma, relaxedgamma, mixedgamma, arc, carc, or mixedcarc)
    default:
      - poisson
      - strictgamma
      - relaxedgamma
      - mixedgamma
  nbIts:
    type: integer
    description: the number of MCMC iterations to perform
    default: 100000000
  thin:
    type: integer
    description: the thining interval between recorded MCMC samples
    default: 100000
  nbac:
    type: integer
    description: the number of replicates per model
    default: 3

  # beautify/BEAST
  clock:
    type: array
    description: the clock models to use (rex [= relaxed exponential], rln [= relaxed lognormal], or str [= strict])
    default:
      - rex
      - rln
      - str
  coal:
    type: array
    description: the coalescent models to use (con [= constant] or exp [= exponential])
    default:
      - con
      - exp
  mcmc_len:
    type: integer
    description: the chain length for MCMC
    default: 100000000
  mcmc_echo:
    type: integer
    description: the sampling frequency for MCMC
    default: 100000
  mle_len:
    type: integer
    description: the chain length for PS/SS MLE
    default: 10000000
  mle_echo:
    type: integer
    description: the sampling frequency for PS/SS MLE
    default: 10000
  mle_step:
    type: integer
    description: the number of path steps for PS/SS MLE
    default: 100
  nbeast:
    type: integer
    description: the number of replicates per clocl+coal model
    default: 3

  # treeannotator
  heights:
    type: string
    description: the heights - an option of 'keep' (default), 'median', 'mean' or 'ca'
    default: median
  burnin:
    type: number
    description: the burnin - the number of states to be considered as 'burn-in', a percentatge in [0, 1]
    default: 0.10
  limit:
    type: number
    description: the limit - the minimum posterior probability for a node to be annotated
    default: 0.50

  # threads
  threads:
    type: integer
    description: the number of threads to use for parallel tasks
    default: 32
