$schema: "http://json-schema.org/draft-06/schema#"

description: the parameters for the measurably-evolving population workflow

properties:
  # ffbio
  acc:
    description: the accession of the query record
  pid:
    type: string
    description: the protein id of the query record
  fdb:
    type: string
    description: the ffbio database of GenBank sequence records

  # BLAST+
  bdb:
    type: string
    description: the BLAST database name
  
  # filter
  tsv:
    type: string
    description: the tab-separated values file mapping "accver" to "date"
    default: False
  thr:
    type: number
    description: the query percent identity coverage >= threshold in [0, 100]
    default: 85

  # Gubbins
  itr:
    type: integer
    description: the maximum number of iterations
    default: 10
  gap:
    type: integer
    description: the value to filter out taxa with more than this percentage of gaps
    default: 25

  # BactDating
  mod:
    type: array
    description: the models to use (poisson, negbin, strictgamma, relaxedgamma, mixedgamma, arc, carc, or mixedcarc)
    default:
      - poisson
      - strictgamma
      - relaxedgamma
      - mixedgamma
  thn:
    type: integer
    description: the thining interval between recorded MCMC samples
    default: 1
  nbi:
    type: integer
    description: the number of MCMC iterations to perform
    default: 250000
  rep:
    type: integer
    description: the number of replicates per model
    default: 3

  # output
  out:
    type: string
    description: the ouput directory
    default: out
